### ISSUE TITLE
Drupal 8 

### ISSUE THREAD

**Issue by feldmarv** [Gizra/entitiesdiagram#1]
This would be absolutely great in DRUPAL 8 with all entities not only node!

**Comment by amitaibu** [comment]
Sounds like a great idea. Care to give it a shot? :)

**Comment by gh640** [comment]
I'm sorry for interference.

If it's not too late, I'd like to try beginning a Drupal 8 branch.

I created a trial branch which works with Drupal 8.x in my forked repository. (It is mostly based on procedural styles and can be improved in many aspects.)

https://github.com/gh640/entitiesdiagram/tree/8.x-1.x

If a branch for 8.x is created in this repo, I'd like to send a pull request. Thank you in advance :)

**Comment by gh640** [comment]
Please note that there are 3 types of diagram page as Drupal 7 version has if you would kindly check this.

- All content entity types: http://example.com/admin/reports/entities-diagram
- Single entity type: http://example.com/admin/reports/entities-diagram/node
- Single entity type with field: http://example.com/admin/reports/entities-diagram/node/true

**Comment by bricel** [comment]
Hi there is already an other module for D8, https://www.drupal.org/project/erd

**Comment by amitaibu** [comment]
@gh640 hi! don't worry, If want other D8 stuff, I have a few nice tasks in OG8 :)

**Comment by gh640** [comment]
@bricel thank you for your reply. It looks good :)

@amitaibu Konichiwa, Amitai san! Yes, I'd like to participate and tackle D8 tasks. Could you please let me know them? Thanks.

**Comment by andypost** [comment]
Here's another implementation we are using for d8 and making ready for d9 https://github.com/skilld-labs/entity_relationship

**Comment by waspper** [comment]
Any plan to release/provide a D8 version? We already have a working codebase (see comment above).

**Comment by amitaibu** [comment]
@andypost @waspper sounds great. There isn't a plan to port this module to D8, so looking forward to using your module when needed :)

**Comment by waspper** [comment]
FYI: We've made a release at https://www.drupal.org/project/entity_relationship_diagram. If needed, we can to join forces there :)
